# Chapter 2

## importing the libraries

In [22]:
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

## importing the dataset

In [23]:
house = pd.read_csv('housing.csv')

FileNotFoundError: [Errno 2] No such file or directory: 'housing.csv'

## Exploring the dataset

In [14]:
house.dtypes

longitude             float64
latitude              float64
housing_median_age    float64
total_rooms           float64
total_bedrooms        float64
population            float64
households            float64
median_income         float64
median_house_value    float64
ocean_proximity        object
dtype: object

In [18]:
house.sample(15)

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
159,-122.24,37.81,52.0,2093.0,550.0,918.0,483.0,2.7477,243800.0,NEAR BAY
6326,-117.96,34.00,33.0,5462.0,952.0,3527.0,914.0,4.4038,186700.0,<1H OCEAN
9381,-122.47,37.87,36.0,4471.0,618.0,1315.0,582.0,11.5706,500001.0,NEAR BAY
14797,-117.10,32.57,14.0,5058.0,1299.0,3662.0,1193.0,2.3253,133700.0,NEAR OCEAN
12263,-116.89,33.79,12.0,701.0,130.0,434.0,110.0,2.0577,56700.0,INLAND
6525,-118.04,34.06,39.0,1258.0,245.0,988.0,228.0,3.2132,176100.0,<1H OCEAN
10305,-117.78,33.88,16.0,1800.0,238.0,871.0,234.0,6.6678,301900.0,<1H OCEAN
14627,-117.18,32.76,8.0,3694.0,997.0,1297.0,807.0,3.6492,158900.0,NEAR OCEAN
3761,-118.36,34.17,31.0,1939.0,505.0,1584.0,466.0,2.5234,199500.0,<1H OCEAN
3060,-119.14,35.76,30.0,735.0,137.0,421.0,113.0,2.5625,156300.0,INLAND
3872,-118.54,34.21,32.0,2593.0,566.0,1596.0,547.0,3.9886,199200.0,<1H OCEAN
15149,-116.90,32.90,19.0,3090.0,552.0,1621.0,520.0,4.0806,189200.0,<1H OCEAN
9543,-120.73,37.38,37.0,653.0,176.0,827.0,176.0,1.9236,64400.0,INLAND
15026,-117.01,32.77,34.0,3330.0,723.0,1592.0,656.0,2.6678,164200.0,<1H OCEAN
7738,-118.14,33.94,35.0,2987.0,601.0,1561.0,606.0,4.0039,226500.0,<1H OCEAN

In [20]:
house.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value
count,20640.000000,20640.000000,20640.000000,20640.000000,20433.000000,20640.000000,20640.000000,20640.000000,20640.000000
mean,-119.569704,35.631861,28.639486,2635.763081,537.870553,1425.476744,499.539680,3.870671,206855.816909
std,2.003532,2.135952,12.585558,2181.615252,421.385070,1132.462122,382.329753,1.899822,115395.615874
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900,14999.000000
25%,-121.800000,33.930000,18.000000,1447.750000,296.000000,787.000000,280.000000,2.563400,119600.000000
50%,-118.490000,34.260000,29.000000,2127.000000,435.000000,1166.000000,409.000000,3.534800,179700.000000
75%,-118.010000,37.710000,37.000000,3148.000000,647.000000,1725.000000,605.000000,4.743250,264725.000000
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100,500001.000000

In [21]:
house.distribute

AttributeError: 'DataFrame' object has no attribute 'distribute'