In [12]:
import numpy as np
import pandas as pd 
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules
from pyECLAT import ECLAT

In [13]:
df = pd.read_csv('marketb1.csv')

In [14]:
df

,burgers,meatballs,eggs,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,chutney,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,turkey,avocado,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,mineral water,milk,energy bar,whole wheat rice,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,low fat yogurt,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,whole wheat pasta,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,whole wheat pasta,olive oil,cereals,brownies,green tea,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
211,cookies,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
212,olive oil,cookies,mushroom cream sauce,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
213,ground beef,pancakes,cooking oil,gluten free bar,light mayo,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
214,mineral water,french fries,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
transactions = []
for sublist in df.values.tolist():
    clean_sublist = [item for item in sublist if item is not np.nan]
    transactions.append(clean_sublist)

In [16]:
transaction = pd.DataFrame(transactions) 
transaction

,0,1,2,3,4,5,6,7,8,9,10,11,12
0,chutney,None,None,None,None,None,None,None,None,None,None,None,None
1,turkey,avocado,None,None,None,None,None,None,None,None,None,None,None
2,mineral water,milk,energy bar,whole wheat rice,green tea,None,None,None,None,None,None,None,None
3,low fat yogurt,None,None,None,None,None,None,None,None,None,None,None,None
4,whole wheat pasta,french fries,None,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,whole wheat pasta,olive oil,cereals,brownies,green tea,None,None,None,None,None,None,None,None
211,cookies,None,None,None,None,None,None,None,None,None,None,None,None
212,olive oil,cookies,mushroom cream sauce,None,None,None,None,None,None,None,None,None,None
213,ground beef,pancakes,cooking oil,gluten free bar,light mayo,None,None,None,None,None,None,None,None
214,mineral water,french fries,None,None,None,None,None,None,None,None,None,None,None

# Looking for item sets & do not want to have any individual products returned

In [17]:
min_n_products = 2

# Want the min support to 7 but show it as percentage

In [18]:
min_support = 5/len(transactions)

In [19]:
max_length = max([len(x) for x in transactions])

# Creating model

In [20]:
eclat = ECLAT(data=transaction, verbose=3)
eclat.df_bin

100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 105/105 [00:00<00:00, 311.30it/s]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 105/105 [00:00<00:00, 91142.78it/s]
100%|â–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆâ–ˆ| 105/105 [00:00<00:00, 2797.16it/s]

,chocolate,toothpaste,chili,corn,champagne,mayonnaise,chutney,barbecue sauce,tomatoes,cereals,...,grated cheese,cake,magazines,eggplant,pet food,water spray,spinach,protein bar,eggs,avocado
0,0,0,0,0,0,0,1,0,0,0,...,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,1
2,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
3,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
4,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
210,0,0,0,0,0,0,0,0,0,1,...,0,0,0,0,0,0,0,0,0,0
211,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
212,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
213,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
214,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

# Fitting the model with the parameters above

In [ ]:
rule_indices, rule_supports = eclat.fit(min_support=0.04,min_combination=1,max_combination=4,separator=' & ',verbose=True)

Combination 1 by 1

28it [00:00, 94.32it/s]

Combination 2 by 2

378it [00:01, 190.55it/s]

Combination 3 by 3

2979it [00:17, 167.66it/s]

In [ ]:
print(rule_supports)

In [ ]:
print(rule_indices)

In [ ]:
get_ECLAT_supports

In [ ]:
get_ECLAT_indexes

In [ ]:
get_ECLAT_indexes_all, get_ECLAT_supports_all = eclat.fit_all(min_support=0.02,
                                                           separator=' & ',
                                                           verbose=True)

In [ ]:
get_ECLAT_supports_all

In [ ]:
rule_indices, rule_supports = eclat.fit(min_support=min_support, 
                                        min_combination=min_n_products,
                                        max_combination=max_length)

Combination 2 by 2

1326it [00:10, 130.96it/s]

Combination 3 by 3

22100it [03:18, 111.33it/s]

Combination 4 by 4

96171it [10:41, 156.67it/s]

In [ ]:
print(rule_supports)

In [ ]:
print(rule_indices)